version: '3.9'

services:
  db_mysql:
    image: mysql:8.0.33
    container_name: db_mysql_hemodinamia
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_bed_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data_hemodinamia:/var/lib/mysql
    networks:
      - hemodinamia-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p1234']
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: hemodinamia_server
    restart: always
    depends_on:
      db_mysql:
        condition: service_healthy
    environment:
      DATABASE_TYPE: mysql
      DATABASE_HOST: db_mysql
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: 1234
      DATABASE_NAME: db_bed_manager
      PORT: 3000
      PRODUCTION: true
    ports:
      - '3001:3000'
    networks:
      - hemodinamia-network

  client:
    build:
      context: ./cliente-web
      dockerfile: Dockerfile.dev
    container_name: hemodinamia_client
    restart: always
    depends_on:
      - server
    ports:
      - '5174:5173'
    environment:
      VITE_API_URL: http://localhost:3001
    networks:
      - hemodinamia-network
    volumes:
      - ./cliente-web:/app
      - /app/node_modules

volumes:
  mysql_data_hemodinamia:

networks:
  hemodinamia-network:
    driver: bridge
